@ApiBaseUrl = http://localhost:5001/api
@TodoId = 68bb30cf1c2327559042a268


### Get All Todos
GET {{ApiBaseUrl}}/todos
Accept: application/json

### Get Todo by ID
GET {{ApiBaseUrl}}/todos/{{TodoId}}
Accept: application/json

### Create a New Todo
POST {{ApiBaseUrl}}/todos
Content-Type: application/json
Accept: application/json

{
  "name": "Find the Holy Grail",
  "completed": false
}

### Update an Existing Todo
PUT {{ApiBaseUrl}}/todos/{{TodoId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Find the Holy Grail - Updated",
  "completed": true
}

### Delete a Todo
DELETE {{ApiBaseUrl}}/todos/{{TodoId}}
Accept: application/json
